# nastaveni.conf pro výpočet RTKPOST

pos1-posmode       =kinematic  # Výpočet polohy pro každou epochu
pos1-frequency     =l1         # Použijeme pouze L1 frekvenci
pos1-elmask        =15         # Elevační maska 15° (odstraní největší multipath z nízkých úhlů)
pos1-snrmask_r     =on         # Zapnutí masky podle síly signálu (SNR/C/N0)
pos1-snrmask_L1    =35,35,35,35,35,35,35,35,35 # Zahození satelitů se signálem pod 35 dB-Hz
pos1-ionoopt       =brdc       # Použití Broadcast modelu ionosféry (kompenzace chyby z atmosféry)
pos1-tropopt       =saas       # Použití Saastamoinenova modelu pro troposféru
out-solformat      =xyz        # Výstup v kartézských souřadnicích (nebo 'llh' pro zeměpisnou šířku/délku)
out-outhead        =on         # Vypíše hlavičku do výsledného souboru
out-outstat        =residual   # Důležité pro BP: Vypíše i statistiku a rezidua pro analýzu
ant2-postype       =rinexhead  # Načte souřadnice báze z hlavičky .26o